// Generated by view binder compiler. Do not edit!
package com.aniketjain.weatherapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aniketjain.weatherapp.R;
import com.github.ybq.android.spinkit.SpinKitView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHomeBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RecyclerView dayRv;

  @NonNull
  public final MainLayoutBinding layout;

  @NonNull
  public final SwipeRefreshLayout mainRefreshLayout;

  @NonNull
  public final SpinKitView progress;

  private ActivityHomeBinding(@NonNull RelativeLayout rootView, @NonNull RecyclerView dayRv,
      @NonNull MainLayoutBinding layout, @NonNull SwipeRefreshLayout mainRefreshLayout,
      @NonNull SpinKitView progress) {
    this.rootView = rootView;
    this.dayRv = dayRv;
    this.layout = layout;
    this.mainRefreshLayout = mainRefreshLayout;
    this.progress = progress;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.day_rv;
      RecyclerView dayRv = ViewBindings.findChildViewById(rootView, id);
      if (dayRv == null) {
        break missingId;
      }

      id = R.id.layout;
      View layout = ViewBindings.findChildViewById(rootView, id);
      if (layout == null) {
        break missingId;
      }
      MainLayoutBinding binding_layout = MainLayoutBinding.bind(layout);

      id = R.id.main_refresh_layout;
      SwipeRefreshLayout mainRefreshLayout = ViewBindings.findChildViewById(rootView, id);
      if (mainRefreshLayout == null) {
        break missingId;
      }

      id = R.id.progress;
      SpinKitView progress = ViewBindings.findChildViewById(rootView, id);
      if (progress == null) {
        break missingId;
      }

      return new ActivityHomeBinding((RelativeLayout) rootView, dayRv, binding_layout,
          mainRefreshLayout, progress);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
